# Generated by Django 4.2 on 2023-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bejegyzes',
            name='osztaly_id',
            field=models.CharField(choices=[('0', 'SZF1A'), ('1', 'SZF1B'), ('2', 'SZF2'), ('3', 'nSZF1A'), ('4', 'nSZF1B')], max_length=10, verbose_name='Osztály'),
        ),
    ]
